### ISSUE TITLE
environment creation command fails, `No module named 'pywin32_bootstrap'`

### ISSUE THREAD

**Issue by amunger** [brettcannon/WWBD#40]
Type: <b>Bug</b>

Opened a workspace, selected an interpreter and ran `WWBD: Create Environment`
I got an error saying it had failed with the logs below, but it looks like it actually succeeded in creating the environment.

logs:

```
$VIRTUAL_ENV is not set
workspace: c:\src\test\5
interpreter: C:\Python310\python.exe
Error processing line 7 of C:\Users\aamunger\AppData\Roaming\Python\Python310\site-packages\pywin32.pth:

  Traceback (most recent call last):
    File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
Traceback (most recent call last):
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\aamunger\.vscode-insiders\extensions\brettcannon.wwbd-2022.1.0\python-src\__main__.py", line 9, in <module>
    main()
  File "c:\Users\aamunger\.vscode-insiders\extensions\brettcannon.wwbd-2022.1.0\python-src\__main__.py", line 5, in main
    runpy.run_module("wwbd", alter_sys=True, run_name="__main__")
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\aamunger\.vscode-insiders\extensions\brettcannon.wwbd-2022.1.0\python-src\wwbd\__main__.py", line 31, in <module>
    main(sys.argv[1:])
  File "c:\Users\aamunger\.vscode-insiders\extensions\brettcannon.wwbd-2022.1.0\python-src\wwbd\__main__.py", line 13, in main
    python_path = wwbd_venv.create(args.workspace)
  File "c:\Users\aamunger\.vscode-insiders\extensions\brettcannon.wwbd-2022.1.0\python-src\wwbd\venv.py", line 24, in create
    venv.create(venv_path, with_pip=True, prompt=prompt)
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\venv\__init__.py", line 423, in create
    builder.create(env_dir)
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\venv\__init__.py", line 313, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\Lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\src\\test\\5\\.venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

Extension version: 2022.1.0
VS Code version: Code - Insiders 1.70.0-insider (e9bda7aa4ff76648cfccc1a7bde465443803da71, 2022-08-02T16:56:25.649Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (13.07GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728

```

</details>

**Comment by amunger** [comment]
never mind, this is just an issue with the environment I'm using - `python -m venv .venv` throws the same error.
